2024FALL-SWPP/team-project-for-2024-fall-swpp-team-12

- Chronus/Assets/Scenes/Levels.unity
- Chronus/Assets/Scenes/Levels.unity.meta
Levels라는 Scene을 만들어서 일단 타일 배치만 했고, 기능 구현은 안 된 상태입니다.
실제로 작동하기 위해 추가적인 태스크 배치도 필요해보입니다.
> [L-001] 튜토리얼 레벨 배치

- Chronus/Assets/Scenes/Field.unity
- Chronus/Assets/Scripts/PhantomController.cs
- Chronus/Assets/Scripts/PhantomController.cs.meta
- Chronus/Assets/Scripts/PlayerController.cs
- Chronus/Assets/Scripts/PlayerHop.cs
- Chronus/Assets/Scripts/PlayerIdle.cs
- Chronus/Assets/Scripts/PlayerMove.cs
- Chronus/Assets/Scripts/PlayerTurn.cs
- Chronus/Assets/Scripts/StateMachine.cs
- Chronus/Assets/Scripts/TurnManager.cs
- Chronus/Assets/Scripts/TurnManager.cs.meta
F-004(Turn system, Player's Log save/edit) <-merge-> Develop(Animator, rabbit model)
> [F-004] 플레이어 이동 경로 저장

- Chronus/Assets/Scripts/PlayerController.cs
command log mistake correction)
added private string type variable curKey, which gets keyboard inputs.
when players do action, command log list gets string value of curKey variables. (w,s,a,d, or r)
rotate in its place when beside wall or void)
when void or wall is the orientation: 
when they are in front of player: do nothing
when they are not in front of player: player rotates in its place and turn updates.
preparation for F-022)
wrote if-else about Lever and Box condition. (not working yet, because I put condition bool value to 'false'.)
just wrote some comments to explain what and how to implement in F-022.
> F-023 complete (command log mistake correction, rotate in its place when beside wall or void)

- Chronus/Assets/Scenes/Test.unity
- Chronus/Assets/Scenes/Test.unity.meta
- Chronus/Assets/Scripts/Character/CharacterBase.cs
약간?의 리팩토링도 곁들였습니다.
Test scene에서 테스트해볼 수 있습니다.
> [F-028] Fixed Raycast in CharacterBase

- .github/pull_request_template.md
- .github/workflows/linter.yml
- PR template 추가
- Linter workflow 추가
> [F-030] PR template 및 Linter workflow 추가

- .github/pull_request_template.md
- .github/workflows/linter.yml
- PR template 추가
- Linter workflow 추가
main에 들어가있어야 되는 것 같아서 다시 올립니다. main에 위 두개만 추가된 걸 commit 해서 다시 올립니다.
> [F-030] PR template 및 Linter workflow 추가 (to main)

- Chronus/Assets/Scenes/LevelBaseScene.unity
- Chronus/Assets/Scenes/Tutorial/L-001-1.unity
- Chronus/Assets/Scenes/Tutorial/L-001-2.unity
- Chronus/Assets/Scenes/Tutorial/L-001-3.unity
- Chronus/Assets/Scripts/LevelManager.cs
[F-032] 
이제 모든 레벨 씬에는 CameraOffsetAnchor가 있어야 합니다.
- 
- 일단 L-001-1~3만 추가해뒀습니다.
---
---
linter.yml:
> [F-032] different camera offset for each levels

- Chronus/Assets/Scripts/Character/CharacterHop.cs
- Chronus/Assets/Scripts/Character/CharacterIdle.cs
- Chronus/Assets/Scripts/Character/CharacterMove.cs
- Chronus/Assets/Scripts/Character/CharacterTurn.cs
- Chronus/Assets/Scripts/Object/MovingObstacle.cs
F-034
generalization of gap, maxgap (not constant (2.0f), but can change by targetTranslation)
moving obstacles push gap also generalized.
character smooth action
- no teleport when move, hop, turn
- modified some hyperparameters
- Move (movingObstacle) invoke time: 0.2f -> 0.15f
- smallHopRate: turn 1.3f, move 1.7f, hop 3.0f
- [o] Added new feature(s)
- [o] Fixed identified bug(s)
- [o] Updated relevant documentation
슬랙 영상 대체
---
---
linter.yml:
> F 034: character smooth action(lotta bug fix), generalization of gap

- Chronus/Assets/Scenes/L-003-1.meta
- Chronus/Assets/Scenes/L-003-1/Field.unity
- Chronus/Assets/Scenes/L-003-1/Field.unity.meta
L-003-1 
There are 3 mini games in the stage that have been completed, each level has different methods to complete the stage. After you complete each mini game,  player can move to the "straight" path at the end of the level.
- [o] 3 Mini Games
- [o] Materials
- [o] Fixed lever position to account for rigidbody
---
---
linter.yml:
> [L-003] Level Finished All 3 Mini Games and Applied Materials

- Chronus/Assets/Art/3D Models/Materials/Brass.mat
- Chronus/Assets/Scenes/Field.unity
- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Character/CharacterHop.cs
- Chronus/Assets/Scripts/Character/PhantomController.cs
- Chronus/Assets/Scripts/Character/PlayerController.cs
- Chronus/Assets/Scripts/Object/Box.cs
- Chronus/Assets/Scripts/Object/Button.cs
- Chronus/Assets/Scripts/Object/Laser.cs
- Chronus/Assets/Scripts/Object/Lever.cs
- Chronus/Assets/Scripts/TurnManager.cs
F-031
Link or reference any related issues or tickets.
Laser death timing correction
before) touch -> kill immediately => problem: moving obstacles time rewind bug
after) touch -> bool var on -> check that var before Fall, and during Fall (CharacterBase)
smaller Button
to hide button under the box
(and edited some values to make better visual)
Box size Generalize
raycast distance determined by box y scale
fall end -> y position ceil also generalized. (determined by box y scale)
Hop-push bug fix
'Hop' 180 degree towards moving obstacles: teleport bug
fixed it.
box-character co-Falling
box (not dying) and characters fall simultaneously.
- [o] Added new feature(s)
- [o] Fixed identified bug(s)
- [o] Updated relevant documentation
Any specific instructions or points to be considered by the …
> [F-031] Many Bug Fixes

- Chronus/Assets/Prefabs/Objects/Lever.prefab
- Chronus/Assets/Scenes/Field.unity
- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Character/PhantomController.cs
- Chronus/Assets/Scripts/Character/PlayerController.cs
- Chronus/Assets/Scripts/LevelManager.cs
- Chronus/Assets/Scripts/Object/Box.cs
- Chronus/Assets/Scripts/Object/Button.cs
- Chronus/Assets/Scripts/Object/Laser.cs
- Chronus/Assets/Scripts/Object/Lever.cs
- Chronus/Assets/Scripts/TurnManager.cs
- Chronus/Assets/Scripts/UI & Effects/RewindManager.cs
- Chronus/Assets/Scripts/UI & Effects/TimeRewindEffect.cs
- Chronus/ProjectSettings/TagManager.asset
Link or reference any related issues or tickets.
Death-TimeRewind Bug Fix)
시간되돌리기 이펙트도 특정 상황때 입력 제한을 걸었습니다. (구현이 안 되어 있어서 구현했습니다)
게임오버 시 깜빡이는 이펙트 - 리셋 전 깜빡일 때는 입력 제한을 걸고,
리셋 후 깜빡일 때는 입력 제한을 푸는 방식으로 수정했습니다.
Button Bug Fix)
버튼(발판)을 계속 누르고 있는 상황에서 발판 카운트가 제대로 업데이트 되지 않는 문제를 해결했습니다.
Undo Phantom bug fix)
Phantom이 일을 마치고 사라진 후에 Undo 시 phantom을 다시 나타나게 만들었습니다.
Phantom이 생성되기 전까지 Undo 시 게임이 작동을 멈추는 버그를 수정했습니다.
LayerMask Fix)
Tag)
플레이어, 분신 - "Player" (둘이 구분할 때는 name으로 구분함)
박스 - "Box"
나머지들 - 상관없음
Layer)
플레이어, 분신 - 3 (Player)
레버 본체 (parent) - 6 (Lever)
레버 막대기 (child) - 7 (LeverStick)
발판(button) - 2 (Ignore Raycast)
나머지들 - 0 (default)
LayerMask)
박스 - 0,3,6번 감지
플레이어, 분신 - 0, 6번 감지
레이저 - 0,3,7번 감지
위 원칙대로 코드를 작성하고 field scene 및 프리팹 일부를 수정했습니다.
Box StampKill Character)
박스가 캐릭터 (플레이어, 분신) 위로 떨어지면 캐릭터를 죽이게 …
> F-031-1 Many Bug Fixes + LayerMask fix

- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Testing/InputManagerTesting.cs
Link or reference any related issues or tickets.
Testing code InputManagerTesting.cs was made inside the testing folder inside scripts folder. Empty GameObject with the InputManagerTesting.cs was made, and on the inspector, a specific case can be chosen. If the game is run, the player will automatically move according to the input sequence of each case. In the code, it is written for each case what it is supposed to test. 
- [o] New script InputManagerTesting.cs
- [o] New gameobject in the hierarchy with InputManagerTesting.cs attached
---
--- …
> [F-037] Testing for [F-035] corner cases and extra simpler cases

- .github/workflows/linter.yml
- .jscpd.json
- Chronus/Assets/Scripts/Object/Box.cs
- Chronus/Assets/Scripts/Object/MovingObstacle.cs
- Chronus/Assets/Scripts/Testing/InputManagerTesting.cs
F-038
Fixed all lint errors including the JSCPD error. Made super-linter to exclude the JSCPD test. Made new logic to test JSCPD separately. 
- [o] All lint errors are fixed
- [o] Modified linter.yml to use separate step/logic for JSCPD, and not do JSCPD in super-linter
---
---
linter.yml:
> [F-038] Github Lint Error Fix (Including JSCPD)

- Chronus/Assets/Scenes/TestField.unity
- Chronus/Assets/Scripts/InputManager.cs
- Chronus/Assets/Scripts/Testing/InputManagerTesting.cs
F-037
Testing code InputManagerTesting.cs was made inside the testing folder inside scripts folder. Empty GameObject with the InputManagerTesting.cs was made in the TestField scene, and on the inspector, a specific case can be chosen. If the game is run, the player will automatically move according to the input sequence of each case. In the code, it is written for each case what it is supposed to test.
- [o] New gameobject in the hierarchy with InputManagerTesting.cs attached
---
---
linter.yml:
> [F-037] Testing in TestField Scene

- Chronus/Assets/Scenes/L-002/L-002-1.unity
- Chronus/Assets/Scenes/L-002/L-002-2.unity
- Chronus/Assets/Scenes/L-002/L-002-3.unity
- Chronus/Assets/Scenes/L-003/L-003-1.unity
- Chronus/Assets/Scenes/L-003/L-003-2.unity
- Chronus/Assets/Scenes/L-003/L-003-3.unity
- Chronus/Assets/Scenes/L-003/L-003-4.unity
- Chronus/Assets/Scenes/L-004/L-004-1.unity
- Chronus/Assets/Scenes/L-004/L-004-2.unity
- Chronus/ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
F-041
카메라 오프셋 조정
---
---
linter.yml:
> [F-041] adjusting camera offsets of levels

- Chronus/Assets/Art/3D Models/Character/MainCharacter.controller
- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Character/CharacterTurn.cs
D-016
Fixed CharacterBase.cs to do animation when the character rotates in place. Not done in CharacterTurn.cs as isMoving and isTurning90/isTurning180 are both triggered. 
- [o] Fixed CharacterBase.cs to do animation when turning in place.
---
---
linter.yml:
> [D-016] Testing Turn Animation

- Chronus/Assets/Art/3D Models/Character/MainCharacter.controller
- Chronus/Assets/Scenes/TestField.unity
- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Character/CharacterMove.cs
D-017
CharacterBase.cs and CharacterMove.cs modified so that only isPushing is true when pushing box. Animation speed set to 3 to make it look more natural.
- [o] Fixed CharacterBase.cs and CharacterMove.cs to do push animation
---
---
linter.yml:
> [D-017] Testing Push Animation

- .jscpd.json
- Chronus/Assets/Scenes/TestField.unity
- Chronus/Assets/Scripts/Testing/InputManagerTesting.cs
F-048
Added more complicated test cases. F-035 corner cases and falling are tested with stacked boxes (either 2 or 3).
- [o] Added new test cases
---
---
linter.yml:
> [F-048] Added Extra Test Cases

- Chronus/Assets/Art/3D Models/Character/MainCharacter.controller
- Chronus/Assets/Scripts/Character/CharacterBase.cs
- Chronus/Assets/Scripts/Character/CharacterMove.cs
- Chronus/Assets/Scripts/Character/CharacterTurn.cs
- Chronus/Assets/Scripts/Character/PhantomController.cs
- Chronus/Assets/Scripts/Character/PlayerController.cs
- Chronus/Assets/Scripts/Object/MovingObstacle.cs
- Chronus/Assets/Scripts/TurnManager.cs
D-017-3
원래: 새로운 함수 만들어서 애니메이터 변수 조정함
바뀐 거: 기존 함수 안에 애니메이터 변수 조정하는 거 넣음
1. 코드 리팩토링
별도의 함수를 만들어 애니메이터 관련 변수를 조정했던 것을 수정하여,
기존 코드 내의 흐름 내에서 올바르게 변수를 조정하도록 하였다.
이 덕분에 movingobstacle버그도 자연스래 해결되었다 (코드 계산량이 줄어들어 invoke time과 어긋나는 일이 사라진 것으로 추측)
그래서 기존에 해당 버그를 수정하려고 invoke time을 0.3으로 늘렸던 걸 다시 0.15로 롤백했다.
2. 애니메이션 속도 값 조정, turn state에서의 small hop (작게 포물선모양으로 뛰어오르기) 수치 조정
---
---
linter.yml:
> [D-017-3] Animation Code Edit

- Chronus/Assets/Scripts/Character/PhantomController.cs
- Chronus/Assets/Scripts/Character/PlayerController.cs
- Chronus/Assets/Scripts/LevelManager.cs
- Chronus/Assets/Scripts/Object/Box.cs
- Chronus/Assets/Scripts/TurnManager.cs
F-055
Pushing Animation Reset when
TimeRewind, Undo, Reset, Gameover
+ run KillPhantom() when isPhantomExisting is true.
- [o] Added new feature(s)
- [o] Fixed identified bug(s)
- [o] Updated relevant documentation
x
---
---
linter.yml:
> [F-055] Pushing Animation Reset

- Chronus/Assets/Prefabs/Objects/Lever.prefab
- Chronus/Assets/Scenes/L-002/L-002-1.unity
- Chronus/Assets/Scenes/L-003/L-003-4.unity
- Chronus/Assets/Scenes/L-004/L-004-1.unity
- Chronus/Assets/Scenes/L-004/L-004-2.unity
- Chronus/Assets/Scenes/L-004/L-004-3.unity
- Chronus/Assets/Scripts/Character/PlayerController.cs
- Chronus/Assets/Scripts/InputManager.cs
- Chronus/Assets/Scripts/LevelManager.cs
- Chronus/Assets/Scripts/Object/Box.cs
- Chronus/Assets/Scripts/Object/Button.cs
- Chronus/Assets/Scripts/Object/Lever.cs
- Chronus/Assets/Scripts/Object/MovingObstacle.cs
- Chronus/Assets/Scripts/TurnManager.cs
- Chronus/Assets/Scripts/UI & Effects/RewindManager.cs
- Chronus/ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
F-044 ~ 047
버그들 전부(아마도) 디버깅 완료. 
리팩토링 한 부분:
1) MovingObstacle -> HandlePush로 wrap up
2) 레버/버튼에 의해 활성화/비활성화되는 오브젝트를 위해 gameObject.activeSelf 판정 추가
3) TurnManager의 InitializeObjectList -> LINQ로 수정
L-004-2, L-004-3은 아직 테스팅해보지는 않았습니다.
---
---
linter.yml:
> [F-044~047] Debugging lots of errors 

- Chronus/Assets/Scenes/LevelBaseScene.unity
F-039
Change the game instruction UI position for tutorial level 
---
---
linter.yml:
> [F-039-1] 튜토리얼 레벨 조작키 위치 수정

- Chronus/Assets/Scenes/L-004/L-004-1.unity
- Chronus/Assets/Scenes/L-004/L-004-2.unity
- Chronus/Assets/Scenes/L-004/L-004-3.unity
L-004
Button Turn Counts Changed to 1
- [o] Button Turn Counts Changed to 1
---
---
linter.yml:
> [L-004] Button Turn Counts Changed to 1

- Chronus/Assets/Scenes/L-002/L-002-3.unity
- Chronus/Assets/Scenes/L-004/L-004-1.unity
Link or reference any related issues or tickets.
L-002-3: change the slightly-off-positioned tile
L-004-1: delete the embedded wall and change the color of stair
---
---
linter.yml:
> Change off-position tile and tile color
